# directory of the kitti dataset
dataset_dir: '/home/ma/kitti00/dataset/sequences/00/'

# whether ouput the pose to txt file or not
output_pose: false

# whether use rviz visualization or not
use_rviz: true

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50
